# Generated by Django 5.0.6 on 2024-07-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.TextField()),
                ('country', models.TextField()),
                ('address', models.TextField()),
                ('telephone', models.TextField()),
                ('description', models.TextField()),
                ('photo', models.TextField()),
            ],
        ),
    ]
